services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend

  mongo:
    image: mongo
    restart: always
    volumes: 
      - ./backend/mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
      ME_CONFIG_BASICAUTH: false
  
  backend:
    depends_on:
      - mongo
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    # restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    # environment:
    #   - DB_HOST=mongodb
    #   - DB_USER=$MONGODB_USER
    #   - DB_PASSWORD=$MONGODB_PASSWORD
    #   - DB_NAME=$MONGODB_DATABASE
    #   - DB_PORT=$MONGODB_DOCKER_PORT
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./src
    #       target: /usr/app
    #       ignore: 
    #         - /node_modules
    #     - action: rebuild
    #       path: package.json
    stdin_open: true
    tty: true
    command: npm run dev